//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControleCarrosVanderson.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BancoCarrosEntities1 : DbContext
    {
        public BancoCarrosEntities1()
            : base("name=BancoCarrosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FABRICANTE> FABRICANTE { get; set; }
        public virtual DbSet<MARCA> MARCA { get; set; }
        public virtual DbSet<SERVICOS> SERVICOS { get; set; }
        public virtual DbSet<CARROS> CARROS { get; set; }
    }
}
