//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaControleCarrosVanderson.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICOS
    {
        public int IDSERVICO { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<int> ANO { get; set; }
        public string PLACA { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<double> PRECO { get; set; }
        public string GARANTIA { get; set; }
        public string OBSERVACOES { get; set; }
        public Nullable<int> FABRICANTE { get; set; }
        public Nullable<int> MARCA { get; set; }
        public Nullable<int> CARRO { get; set; }
        public Nullable<System.DateTime> FINAL_GARANTIA { get; set; }
    
        public virtual FABRICANTE FABRICANTE1 { get; set; }
        public virtual MARCA MARCA1 { get; set; }
        public virtual CARROS CARROS { get; set; }
    }
}
